### ISSUE TITLE
Make OpenMP a feature dependent on compiler support

### ISSUE THREAD

**Issue by awvwgk** [dftd3/simple-dftd3#102]
Apple clang as C compiler does not support OpenMP, therefore when building on MacOS with the default C compiler rather than failing the build for not finding OpenMP, the OpenMP feature could be disabled due to missing compiler support automatically.

Note: This might silently remove features like parallelization for users on MacOS when not carefully building the library.

**Comment by AlexBuccheri** [comment]
Another option might be to tell the user Apple clang is detected, and that they should either specify their fortran compiler at cmake configure time, or disable OMP with something like `-DENABLE_OpenMP=Off`. Then the user is explicitly makes the the choice
