### ISSUE TITLE
Build Python wheels for MacOS / Windows?

### ISSUE THREAD

**Issue by awvwgk** [dftd3/simple-dftd3#16]
Currently Python wheels are only built for Linux using mesonpep517, since the conda-forge distribution already covers MacOS and Windows this seems like only minor issue. However, if there is sufficient interest and/or somebody is willing to contribute the respective additions to the wheel building workflow the distribution can be expanded.

Preferably we can also build Python wheels for MacOS and Windows against the conda-forge API like done in the Linux case.

**Comment by metma99** [comment]
Hello:
I just saw you post, and I would like to ask you to create the dftd-phython build for Mac OS arm.
When I run `conda install dftd3-python -c C=conda-forge` I am getting that the package is not available. When I run `pip install dftd3-python` no matching distribution is found.
I tried to build from scratch but have not been successful so far.
Thank you very much in advance,
Markus

**Comment by awvwgk** [comment]
There is currently no build for OSX/Arm64 on conda-forge, the version from PyPI however should build from source with `pip install dftd3` (no need to specify `-python` for a Python package).
