### ISSUE TITLE
Parameters for B97-3c

### ISSUE THREAD

**Issue by hebrewsnabla** [dftd3/simple-dftd3#24]
I'm trying to implement B97-3c (https://aip.scitation.org/doi/10.1063/1.5012601) in PySCF with help of this lib. But it seems B97-3c is not  in parameters.toml. Could it be added?

**Comment by awvwgk** [comment]
Feel free to open a PR. There is an internal database in https://github.com/dftd3/simple-dftd3/blob/main/src/dftd3/param.f90 and an external one in https://github.com/dftd3/simple-dftd3/blob/main/assets/parameters.toml, where parameters can be added.

**Comment by hebrewsnabla** [comment]
> Feel free to open a PR. There is an internal database in https://github.com/dftd3/simple-dftd3/blob/main/src/dftd3/param.f90 and an external one in https://github.com/dftd3/simple-dftd3/blob/main/assets/parameters.toml, where parameters can be added.

Should I update both of them?
