### ISSUE TITLE
sdist workflow is broken

### ISSUE THREAD

**Issue by awvwgk** [dftd3/simple-dftd3#30]
Cannot find ninja when running meson from mesonpy build backend.

**Comment by eli-schwartz** [comment]
Guessing this is probably https://github.com/scikit-build/ninja-python-distributions/issues/157 which should be fixed now?

**Comment by awvwgk** [comment]
Thanks for the hint, probably will switch to provisioning this workflow with conda-forge rather than PyPI then.
