### ISSUE TITLE
Reliability of combining simple DFT-D3 and VASP with ASE interface?

### ISSUE THREAD

**Issue by qiuyunze** [dftd3/simple-dftd3#41]
Recently, I'm using simple DFT-D3 and VASP with ASE interface because some DFT-D3 parameters are not set as default in VASP. Here is part of my script:

```python
from dftd3.ase import DFTD3
from ase.calculators.vasp import Vasp
from ase.calculators.mixing import SumCalculator
from ase.io import read, write
from ase.optimize import LBFGS, BFGS, GPMin

atoms = read('CONTCAR')
d3 = DFTD3(method='PBE', damping='d3bj')   
vasp_pbe.set(label='PBE', directory='PBE', xc='PBE') # check whether the energy is consistent with the default one in VASP
vasp_pbe_d3 = SumCalculator([d3, vasp_pbe])
del atoms.constraints
atoms.set_calculator(vasp_pbe_d3)
dyn=LBFGS(atoms)    #优化器
dyn.run(fmax=0.03)
``` 

To verify the scheme, I used CO adsorption energy as a criterion and compared the difference between simple DFT-D3 and default one in VASP. I found that the absolute energy for a specific structure is different, while the targeted adsorption energy is quite close.
![Snipaste_2023-07-04_06-06-31](https://github.com/dftd3/simple-dftd3/assets/72092595/27cfd5fd-53f4-4538-b52e-6407b197a750)

**However, I'm still worried about the reliability of  such a scheme and do you have any suggestions?**

**Comment by awvwgk** [comment]
I'm using different real-space cutoffs for evaluating the dispersion energy from the implementation in Vasp. The cutoffs can be adjusted to match with the ones used in Vasp to exactly match in the computed dispersion energies if needed. Overall, I am not worried about the reliability of the slight difference in the results.

**Comment by qiuyunze** [comment]
Cool, thank you for your prompt reply.
