### ISSUE TITLE
PySCF interface retrieves incorrect atomic numbers if ECPs are used

### ISSUE THREAD

**Issue by awvwgk** [dftd3/simple-dftd3#72]
See https://github.com/dftd4/dftd4/issues/247

**Comment by marvinfriede** [comment]
Actually, D3 does not use `mol.atom_charges()`, but instead correctly uses the atomic symbols to retrieve the charge. The conversion is correct (see [here](https://github.com/dftd3/simple-dftd3/blob/a13813a6929ebd2a83ab7d33a023edffecd3f0c7/python/dftd3/pyscf.py#L224)).
