### ISSUE TITLE
instructions on how to install ninja, CMake, fpm, and other package build approaches.

### ISSUE THREAD

**Issue by shahmoradi** [dftd3/simple-dftd3#89]
While the multiple-build approaches are admirable and relatively comprehensive, some non-default build systems (such as Ninja) may be challenging for some users on specific platforms. For example, despite frequent programming in Fortran, I have rarely used FPM. Could you add a brief set of instructions to the installation documents explaining how to install the relevant build systems like those mentioned above? I suppose improvements as simple as pointers to the relevant websites or downloads via popular package managers could achieve the goal. These pointers could also help further publicize these tools.

**Comment by awvwgk** [comment]
The current installation guide at https://dftd3.readthedocs.io/en/latest/installation.html#building-from-source mentions all build systems, but it should be linked more prominently in the project readme.

**Comment by AlexBuccheri** [comment]
This was also my feeling, the top-level README would benefit from specifying(or pointing to) a list of external dependencies, and provide details on installation of the lib (specification of prefix install path and install command) for cmake. It took me a while of rummaging through to find some details, and I think I still missed the reference linked above by @awvwgk
