### ISSUE TITLE
dRPA75-D3(BJ) and  SCS-dRPA75-D3(BJ) from MRCC

### ISSUE THREAD

**Issue by foxtran** [dftd3/simple-dftd3#93]
In MRCC, there is another definition of parameters of dRPA75-D3(BJ) and  SCS-dRPA75-D3(BJ)

dRPA75-D3(BJ):
s6 = 0.375_wp (should be 0.3754_wp according to reference)
a2 = 4.505_wp (should be 4.5048_wp according to reference)

SCS-dRPA75-D3(BJ) uses the same dispersion parameter as dRPA75-D3(BJ).

**Comment by awvwgk** [comment]
I don't have access to the MRCC source code to check. Could you share the origin of these parameters used in MRCC with me?

**Comment by foxtran** [comment]
I have no idea why these parameters are chosen. For dRPA75, it looks like it was rounded up to three-four digits, for SCS-dRPA75 it is a question.

The source code is:
```
         else if(trim(dft).eq.'drpa75') then
          call ishell('echo "0.375 0.0000 0.000 4.505 0.0000 4" >' //
     $'$HOME/.dftd3par.`hostname`')
          call runit('dftd3 COORD.xyz -bj'//cg,cput,walt)
          call ishell('rm -f $HOME/.dftd3par.`hostname`')
          call edispprint('dRPA75-D3       ',cput,walt,subsys)
         else if(trim(dft).eq.'scs-drpa75') then
          call ishell('echo "0.375 0.0000 0.000 4.505 0.0000 4" >' //
     $'$HOME/.dftd3par.`hostname`')
          call runit('dftd3 COORD.xyz -bj'//cg,cput,walt)
          call ishell('rm -f $HOME/.dftd3par.`hostname`')
          call edispprint('SCS-dRPA75-D3   ',cput,walt,subsys)
```

Currently, removed by me.

**Comment by awvwgk** [comment]
Going forward any parameter addition to DFT-D3 will require proper attribution. For MRCC specific versions of dRPA75 this means that either a reference to these parameters can be provided or MRCC needs to handle these custom parameters itself without having simple keywords.
