### ISSUE TITLE
More functionals from 10.1002/jcc.23391

### ISSUE THREAD

**Issue by foxtran** [dftd3/simple-dftd3#94]
A huge list of parameters for a set of functionals was presented in 10.1002/jcc.23391. Unfortunately, only 2-digit precision is. See the SI of this paper.

**Comment by awvwgk** [comment]
An extensive list of functionals, I believe the damping parameters are accurate with two digits.

<img width="719" alt="image" src="https://github.com/user-attachments/assets/5b01646c-578b-4d19-8196-3c65578cd09e">

**Comment by foxtran** [comment]
> I believe the damping parameters are accurate with two digits.

There is a problem that it is not enough. 

Taking parameters from #92 (s6=0.418, a2=5.65), the dispersion energy for example.xyz is `-1.5172415429713E-02`. With two digits (s6=0.42, a2=5.7), the dispersion energy is `-1.4655518783476E-02`. The difference is ~3.5 % and that is huge.

The output:
```
build % app/s-dftd3 ../app/example.xyz --bj-param 0.418 0.0 0.0 5.65
-----------------------------------
 s i m p l e   D F T - D 3  v1.1.1
-----------------------------------

Rational (Becke-Johnson) damping: D3(BJ)
---------------------
  s6         0.4180
  s8         0.0000
  s9         0.0000
  a1         0.0000
  a2         5.6500
 alp        14.0000
--------------------

Dispersion energy:      -1.5172415429713E-02 Eh

[Info] Dispersion energy written to .EDISP
 build % app/s-dftd3 ../app/example.xyz --bj-param 0.42 0.0 0.0 5.7
-----------------------------------
 s i m p l e   D F T - D 3  v1.1.1
-----------------------------------

Rational (Becke-Johnson) damping: D3(BJ)
---------------------
  s6         0.4200
  s8         0.0000
  s9         0.0000
  a1         0.0000
  a2         5.7000
 alp        14.0000
--------------------

Dispersion energy:      -1.4655518783476E-02 Eh
```

**Comment by foxtran** [comment]
DSD-BLYP is already implemented.
